---
- name: Configure QuickCart Production Web Nodes
  hosts: webservers
  become: true
  tasks:
    - name: Ensure latest security patches
      yum:
        name: "*"
        state: latest

    - name: Install Nginx web server
      package:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy Production HTML
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <body style="text-align:center; font-family:sans-serif; margin-top:50px;">
            <h1 style="color:#232f3e;">QuickCart Production V1</h1>
            <p>Automated via <strong>Ansible Playbook</strong></p>
          </body>
          </html>